Fix total users number in the users index page
rubytr/ruby-tr pull request #191
Opened 2022-06-13 01:07 UTC by mustafasakalli

### Bağlantılı olduğu issue

Resolves #187 

### Kontrol listesi

* [+] Kendi yazdığım kodun özdeğerlendirmesini yaptım
* [+] Gerekliyse anlaşılması zor olan yerleri yorum ekleyerek açıkladım
* [+] Gerekliyse `README.md` dosyası ve dokümanlarda gerekli değişiklikleri yaptım
* [ ] Yazdığım kodun veya düzelttiğim hatanın testlerini ekledim
* [+] `bundle exec rake` komutunu çalıştırdım ve tüm testlerim geçti
* [+] `rubocop` komutunu çalıştırdım ve hiç bir hata almadım
* [ ] Eğer PR'ım yazımı hala devam ediyorsa başlıkta 'WIP' olarak belirttim veya draft PR olarak açtım[draft PR](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests#draft-pull-requests)
* [+] Yaptığım değişiklikleri anlamlı olacak bütünlükte ve ayrı ayrı commitledim.

### Açıklama

### Değişiklik tipi

* Hata düzeltme (uygulamada çok fazla değişikliğe yol açmayan sadece hata çözen değişiklik): **users** kısmındaki topluluklar sayısı pagination dolayısıyla o sayfadaki toplam kullanıcı sayısını gösteriyordu (eğer sayfa tamamen dolu ise bu sayı 25). Bu fix ile birlikte kayıtlı tüm kullanıcıların sayısı gösteriliyor

### Bu PR için hangi testler yazıldı? Ve bu testlerin olası beklenen sonuçları nelerdir?

2022-06-13 07:38 UTC, yasarcelep requested changes
Eline saglik 👌🙌

2022-06-13 07:38 UTC, yasarcelep commented on app/views/users/index.html.erb
> +        <h2>Topluluk (<%= @all_users %>)</h2>
Burada `@users.total_count` ustunden alsak nasil olur? Ya da 'page_entries_info' helper method'unu da kullanabiliriz.

2022-07-01 08:41 UTC, yasarcelep commented
Selam, 
@mustafasakalli test yazacak mısın? :) Yoksa mergeleyelim mi?

2022-07-01 08:41 UTC, yasarcelep approved these changes

2022-07-01 08:45 UTC, mustafasakalli commented
@yasarcelep Selam, isterseniz mergeleyelim

2022-07-01 10:54 UTC, enderahmetyurt approved these changes
Eline saglik 👌🙌

2022-07-01 11:14 UTC, merged